CONFIG_PATH = '/etc/flowd/flowd.cfg'
PID_FILE = '/var/run/flowd.pid'
WORK_DIR = '/var/lib/flowd'
DEFAULT_BACKEND = 'udp_firefly'
NP_API_FILE = '/var/run/flowd'
UDP_FIREFLY_PORT = 5000
IP4_DISCOVERY = ('10.255.255.255', 1)
IP6_DISCOVERY = ('fc00::', 1)
STUN_SERVERS = [('stun.l.google.com', 19305), ('stun.services.mozilla.org', 3478)]
